/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  System: () => import('#controllers/system_controller'),
  weixin: {
    Accounts: () => import('#controllers/weixin/accounts_controller'),
    LoginSessions: () => import('#controllers/weixin/login_sessions_controller'),
    Media: () => import('#controllers/weixin/media_controller'),
    MediaDownload: () => import('#controllers/weixin/media_download_controller'),
    Messages: () => import('#controllers/weixin/messages_controller'),
    Typing: () => import('#controllers/weixin/typing_controller'),
    Webhooks: () => import('#controllers/weixin/webhooks_controller'),
  },
}
