/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WeixinAccountSchema extends BaseModel {
  static $columns = [
    'baseUrl',
    'cdnBaseUrl',
    'createdAt',
    'enabled',
    'encryptedBotToken',
    'id',
    'ilinkUserId',
    'lastError',
    'lastInboundAt',
    'lastOutboundAt',
    'providerAccountId',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = WeixinAccountSchema.$columns
  @column()
  declare baseUrl: string
  @column()
  declare cdnBaseUrl: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare encryptedBotToken: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ilinkUserId: string | null
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare lastInboundAt: DateTime | null
  @column.dateTime()
  declare lastOutboundAt: DateTime | null
  @column()
  declare providerAccountId: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class WeixinConversationSchema extends BaseModel {
  static $columns = [
    'accountId',
    'createdAt',
    'encryptedContextToken',
    'encryptedTypingTicket',
    'id',
    'lastMessageAt',
    'peerUserId',
    'typingTicketExpiresAt',
    'updatedAt',
  ] as const
  $columns = WeixinConversationSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare encryptedContextToken: string | null
  @column()
  declare encryptedTypingTicket: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastMessageAt: DateTime | null
  @column()
  declare peerUserId: string
  @column.dateTime()
  declare typingTicketExpiresAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WeixinLoginSessionSchema extends BaseModel {
  static $columns = [
    'accountId',
    'botType',
    'createdAt',
    'errorMessage',
    'expiresAt',
    'id',
    'ilinkUserId',
    'pollingBaseUrl',
    'qrcode',
    'qrcodeUrl',
    'status',
    'updatedAt',
    'userId',
  ] as const
  $columns = WeixinLoginSessionSchema.$columns
  @column()
  declare accountId: string | null
  @column()
  declare botType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ilinkUserId: string | null
  @column()
  declare pollingBaseUrl: string
  @column()
  declare qrcode: string
  @column()
  declare qrcodeUrl: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class WeixinMessageSchema extends BaseModel {
  static $columns = [
    'accountId',
    'clientMessageId',
    'createdAt',
    'direction',
    'errorCode',
    'fromUserId',
    'id',
    'payload',
    'providerMessageId',
    'providerSeq',
    'receivedAt',
    'sentAt',
    'status',
    'toUserId',
    'updatedAt',
  ] as const
  $columns = WeixinMessageSchema.$columns
  @column()
  declare accountId: string
  @column()
  declare clientMessageId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direction: string
  @column()
  declare errorCode: string | null
  @column()
  declare fromUserId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare payload: string
  @column()
  declare providerMessageId: string | null
  @column()
  declare providerSeq: number | null
  @column.dateTime()
  declare receivedAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare toUserId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WeixinSyncStateSchema extends BaseModel {
  static $columns = ['accountId', 'getUpdatesBuf', 'updatedAt'] as const
  $columns = WeixinSyncStateSchema.$columns
  @column({ isPrimary: true })
  declare accountId: string
  @column()
  declare getUpdatesBuf: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WeixinWebhookDeliverySchema extends BaseModel {
  static $columns = [
    'accountId',
    'attempts',
    'createdAt',
    'deliveredAt',
    'endpointId',
    'eventId',
    'eventType',
    'id',
    'lastError',
    'nextAttemptAt',
    'payload',
    'status',
    'updatedAt',
  ] as const
  $columns = WeixinWebhookDeliverySchema.$columns
  @column()
  declare accountId: string
  @column()
  declare attempts: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare endpointId: string
  @column()
  declare eventId: string
  @column()
  declare eventType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastError: string | null
  @column.dateTime()
  declare nextAttemptAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class WeixinWebhookEndpointSchema extends BaseModel {
  static $columns = [
    'accountId',
    'createdAt',
    'enabled',
    'encryptedSecret',
    'events',
    'id',
    'lastDeliveryAt',
    'updatedAt',
    'url',
    'userId',
  ] as const
  $columns = WeixinWebhookEndpointSchema.$columns
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare encryptedSecret: string
  @column()
  declare events: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastDeliveryAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare url: string
  @column()
  declare userId: number
}
